/**
 * Template Loader
 *
 * Copies a template directory, then injects business data into
 * the template's data layer. Each template has a standard structure
 * that expects data in a specific location.
 *
 * Template structure (expected):
 *   templates/<name>/
 *     src/
 *       data/
 *         business.json       <-- we write this
 *         generated.json      <-- AI content goes here (content-generator)
 *       components/           <-- template components (not modified)
 *       assets/               <-- photos go here (photo-processor)
 *       styles/               <-- template styles (not modified)
 *     next.config.ts          <-- static export config
 *     package.json
 *     tsconfig.json
 */

import { cp, writeFile, mkdir, readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const TEMPLATES_DIR = join(__dirname, "..", "..", "templates");

/**
 * Load a template: copy it to the output directory and inject business data.
 *
 * @param {string} templateName - template directory name (e.g., "hostel", "cafe")
 * @param {import('../../scraper/src/schema.ts').BusinessData} businessData
 * @param {string} outputDir - where to generate the site
 */
export async function loadTemplate(templateName, businessData, outputDir) {
  const templateDir = join(TEMPLATES_DIR, templateName);

  if (!existsSync(templateDir)) {
    throw new Error(
      `Template "${templateName}" not found at ${templateDir}. ` +
      `Available templates: ${await listTemplates()}`
    );
  }

  // Step 1: Copy the entire template to output directory
  console.log(`[template] Copying ${templateName} template to ${outputDir}`);

  if (!existsSync(outputDir)) {
    await mkdir(outputDir, { recursive: true });
  }

  await cp(templateDir, outputDir, {
    recursive: true,
    force: true,
    filter: (src) => {
      // Skip node_modules, .next, out directories
      const name = src.split("/").pop();
      return !["node_modules", ".next", "out", ".DS_Store"].includes(name);
    },
  });

  // Step 2: Write business data into the template's data directory
  const dataDir = join(outputDir, "src", "data");
  if (!existsSync(dataDir)) {
    await mkdir(dataDir, { recursive: true });
  }

  await writeFile(
    join(dataDir, "business.json"),
    JSON.stringify(businessData, null, 2),
    "utf-8"
  );

  console.log(`[template] Business data written to ${join(dataDir, "business.json")}`);

  // Step 3: Update package.json with business-specific values
  await patchPackageJson(outputDir, businessData);

  // Step 4: Inject SEO metadata
  await injectSEOData(outputDir, businessData);

  console.log("[template] Template loaded successfully");
}

/**
 * Update the template's package.json with business-specific name and description.
 */
async function patchPackageJson(outputDir, businessData) {
  const pkgPath = join(outputDir, "package.json");
  if (!existsSync(pkgPath)) return;

  const pkg = JSON.parse(await readFile(pkgPath, "utf-8"));
  pkg.name = businessData.slug;
  pkg.description = `Website for ${businessData.name} — generated by Agnotita`;

  await writeFile(pkgPath, JSON.stringify(pkg, null, 2), "utf-8");
}

/**
 * Write SEO data file that templates use for meta tags, JSON-LD, etc.
 *
 * Templates are expected to import this from `src/data/seo.json`.
 */
async function injectSEOData(outputDir, data) {
  const seo = {
    title: `${data.name} — ${capitalize(data.category)} in ${data.city}`,
    description: data.description || `${data.name} is a ${data.category} in ${data.city}, ${data.state}.`,
    keywords: buildKeywords(data),
    ogImage: data.photos?.[0]?.url || null,
    structuredData: buildStructuredData(data),
  };

  const seoPath = join(outputDir, "src", "data", "seo.json");
  await writeFile(seoPath, JSON.stringify(seo, null, 2), "utf-8");
}

/**
 * Build schema.org structured data based on business category.
 */
function buildStructuredData(data) {
  const baseSchema = {
    "@context": "https://schema.org",
    "@type": categoryToSchemaType(data.category),
    name: data.name,
    description: data.description,
    address: {
      "@type": "PostalAddress",
      streetAddress: data.address,
      addressLocality: data.city,
      addressRegion: data.state,
      addressCountry: "IN",
    },
    telephone: data.phone,
    url: data.website,
    image: data.photos?.slice(0, 5).map((p) => p.url),
  };

  if (data.rating) {
    baseSchema.aggregateRating = {
      "@type": "AggregateRating",
      ratingValue: data.rating,
      reviewCount: data.reviewCount || 0,
      bestRating: 5,
    };
  }

  if (data.coordinates) {
    baseSchema.geo = {
      "@type": "GeoCoordinates",
      latitude: data.coordinates.lat,
      longitude: data.coordinates.lng,
    };
  }

  if (data.hours) {
    baseSchema.openingHoursSpecification = buildOpeningHours(data.hours);
  }

  return baseSchema;
}

function categoryToSchemaType(category) {
  const map = {
    hostel: "Hostel",
    hotel: "Hotel",
    cafe: "CafeOrCoffeeShop",
    restaurant: "Restaurant",
    salon: "BeautySalon",
    coworking: "OfficeSpace",
    gym: "ExerciseGym",
    clinic: "MedicalClinic",
    shop: "Store",
  };
  return map[category] || "LocalBusiness";
}

function buildOpeningHours(hours) {
  const dayMap = {
    mon: "Monday", tue: "Tuesday", wed: "Wednesday",
    thu: "Thursday", fri: "Friday", sat: "Saturday", sun: "Sunday",
  };

  return Object.entries(hours)
    .filter(([, time]) => time && time !== "Closed")
    .map(([day, time]) => {
      const [opens, closes] = parseTimeRange(time);
      return {
        "@type": "OpeningHoursSpecification",
        dayOfWeek: dayMap[day],
        opens,
        closes,
      };
    });
}

function parseTimeRange(timeStr) {
  // Parse "9:00 AM - 10:00 PM" or "09:00-22:00" formats
  const parts = timeStr.split(/[-–]/);
  if (parts.length === 2) {
    return [parts[0].trim(), parts[1].trim()];
  }
  return ["00:00", "23:59"];
}

function buildKeywords(data) {
  const keywords = [
    data.name,
    data.category,
    data.city,
    `${data.category} in ${data.city}`,
    `best ${data.category} ${data.city}`,
  ];

  if (data.amenities?.length) {
    keywords.push(...data.amenities.slice(0, 5));
  }

  return keywords.join(", ");
}

function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

/**
 * List available template names.
 */
async function listTemplates() {
  const { readdir } = await import("node:fs/promises");
  try {
    const entries = await readdir(TEMPLATES_DIR, { withFileTypes: true });
    return entries
      .filter((e) => e.isDirectory())
      .map((e) => e.name)
      .join(", ");
  } catch {
    return "(none)";
  }
}
